In [10]:
import numpy as np

In [11]:
def multiplicar_matrices(matriz1,matriz2):
    
    if len(matriz1[0]) == len(matriz2):
        
        matrizr = np.zeros((len(matriz1[0]),len(matriz2[1])))            
        for i in range(len(matriz1)):
            for j in range(len(matriz2[0])):
                for k in range(len(matriz1[0])):
                    matrizr[i][j] += matriz1[i][k]*matriz2[k][j]
                    
        return matrizr
    else:
        return none

In [12]:
#Comprobacion:
A=[[1,0,0],[5,1,0],[-2,3,1]]
B=[[4,-2,1],[0,3,7],[0,0,2]]

In [13]:
print(multiplicar_matrices(A,B))
print(np.dot(A,B))

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
[[ 4 -2  1]
 [20 -7 12]
 [-8 13 21]]
